# Generated by Django 5.0.4 on 2024-05-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenda', models.ImageField(upload_to='Clothes/')),
                ('categoria', models.CharField(choices=[('camiseta', 'Camiseta'), ('pantalon', 'Pantalón')], max_length=50)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
    ]
