# Generated by Django 5.0.4 on 2024-05-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='categoria',
            field=models.CharField(choices=[('camiseta', 'Camiseta'), ('pantalon', 'Pantalón'), ('zapatos', 'Zapatos')], max_length=50),
        ),
    ]
