# Generated by Django 5.0.4 on 2024-05-29 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wardrobe', '0002_alter_clothes_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='color',
        ),
    ]
