# Generated by Django 5.0.4 on 2024-06-16 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name': 'Garment', 'verbose_name_plural': 'Garments'},
        ),
    ]
