# Generated by Django 5.0.4 on 2024-06-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='categoria',
            field=models.CharField(max_length=50),
        ),
    ]
