<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-06-25 06:46
=======
# Generated by Django 5.0.4 on 2024-06-24 04:07
>>>>>>> 1eb1a4ac8b7da4a6d97457593dcd3dd430436ae9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wardrobe', '0002_alter_clothes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name': 'Prenda', 'verbose_name_plural': 'Prendas'},
        ),
        migrations.AlterField(
            model_name='clothes',
            name='garment',
            field=models.ImageField(upload_to='Clothes/'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='type',
            field=models.CharField(choices=[('casual', 'Casual'), ('formal', 'Formal'), ('deportivo', 'Deportivo')], max_length=10),
        ),
    ]
