# Generated by Django 5.0.4 on 2024-06-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wardrobe', '0002_alter_clothes_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='dominant_color',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='prenda',
            field=models.ImageField(upload_to=''),
        ),
    ]
