# Generated by Django 5.0.4 on 2024-06-25 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Wardrobe', '0003_alter_clothes_options_alter_clothes_garment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitSaving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_saved', models.DateTimeField(auto_now_add=True)),
                ('bottom_clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_outfit', to='Wardrobe.clothes')),
                ('shoe_clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoe_outfit', to='Wardrobe.clothes')),
                ('top_clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_outfit', to='Wardrobe.clothes')),
            ],
            options={
                'verbose_name': 'Outfit',
                'verbose_name_plural': 'Outfits',
            },
        ),
    ]
